# Generated by Django 3.1.3 on 2021-02-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='color',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='date',
        ),
    ]
