# Generated by Django 3.1.3 on 2021-02-06 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_auto_20210206_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timestamp',
            name='panel',
        ),
        migrations.AddField(
            model_name='panel',
            name='timestamp',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='timeline.timestamp'),
            preserve_default=False,
        ),
    ]
