# Generated by Django 3.1.3 on 2021-02-06 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_auto_20210206_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='timestamp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timeline.timestamp'),
        ),
    ]
