# Generated by Django 3.1.3 on 2021-02-06 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_auto_20210206_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='timestamp',
            name='panel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='timeline.panel'),
            preserve_default=False,
        ),
    ]
