# Generated by Django 3.1.3 on 2021-02-06 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0007_auto_20210206_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='timestamp',
            name='date',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='timeline.date'),
            preserve_default=False,
        ),
    ]
