# Generated by Django 3.1.3 on 2021-02-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0008_auto_20210206_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='description',
            field=models.TextField(),
        ),
    ]
