# Generated by Django 3.1.3 on 2021-02-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0011_auto_20210207_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='description',
            field=models.TextField(),
        ),
    ]
